### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 1429904852** [HKUST-KnowComp/RINANTE#3]
请介绍下数据处理的流程，有的数据有点看不懂
举个例子：
（1）the bread is top notch as well .
**0 3 4 9 10 12 13 16 17 22 23 25 26 30 30 31**
i have to say they have one of the fastest delivery times in the city .
**0 1 2 6 7 9 10 13 14 18 19 23 24 27 28 30 31 34 35 42 43 51 52 57 58 60 61 64 65 69 69 70**
下面的一行数字怎么得到的，代表什么意思？

（2）{"id": "32897564#894393#2", "text": "The bread is top notch as well.", "terms": [{"term": "bread", "polarity": "positive", "span": [4, 9]}], "opinions": ["top notch"]}
"span": [4, 9]是怎么得到的？

**Comment by hldai** [comment]
"the bread is top notch as well ."
0 3 4 9 10 12 13 16 17 22 23 25 26 30 30 31

the numbers are the spans of the tokens in the original sentence.
e.g.:
the original sentence is sent="The bread is top notch as well."
sent[0:3] = "The"
sent[4:9] = "bread"

These numbers are obtained with some java code. Not included in this project.

**Comment by 1429904852** [comment]
thank you for your reply
